# Import Email Data 

In [1]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [4]:
emails = pd.read_csv("new_dataset.csv")

''' Convert negative features to positive values'''
# emails.replace(-1, 1, inplace= True)
# emails.replace(0, 2, inplace= True)
# emails.replace(1, 3, inplace= True)


print(type(emails))
# print(emails.head())
# print(emails)

<class 'pandas.core.frame.DataFrame'>


# Save target variable and feature variables in their own objects

In [5]:
y = emails['Result']  # without result as a category type
# y = emails['Result'].astype('category') # as a 'category' type
X = emails.iloc[:,0:29]
# print(X.head())
print(X.shape)
print(y.shape)


(11055, 29)
(11055,)


# Split data into train & test set using scikit learn

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
X_train.shape

(7738, 29)

# Feature Selection using Chi-squared & 'SelectKBest' - (scikit) 

In [9]:
# Feature Extraction with Univariate Statistical Tests (Chi-squared for classification)
import pandas
import numpy
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

# feature extraction
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, y)

# summarize scores
numpy.set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)

# summarize selected features
print(features[0:5,:])

[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
[[3 3 3 3]
 [2 3 3 3]
 [3 3 3 2]
 [3 3 3 3]
 [2 3 3 3]]


# Feature Selection w/ Extra Tree Classifier

In [10]:
# Feature Importance with Extra Trees Classifier
from pandas import read_csv
from sklearn.ensemble import ExtraTreesClassifier

# feature extraction
model = ExtraTreesClassifier()
model.fit(X, y)
print(model.feature_importances_)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


# Gaussian Naive Bayes Classifier 

In [22]:
# Gaussian Naive Bayes
from sklearn import datasets
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

# fit a Naive Bayes model to the data
model = GaussianNB()
model.fit(X_train, y_train)
print(model)

# make predictions
expected = y_test
predicted = model.predict(X_test)

# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

GaussianNB(priors=None)
             precision    recall  f1-score   support

         -1       0.51      1.00      0.68      1428
          1       0.99      0.28      0.43      1889

avg / total       0.79      0.59      0.54      3317

[[1425    3]
 [1367  522]]


# Decision Trees Classifier

In [23]:
# Decision Tree Classifier
from sklearn import datasets
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier

# fit a CART model to the data
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
# print(model)

# make predictions
expected = y_test
predicted = model.predict(X_test)

# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

             precision    recall  f1-score   support

         -1       0.95      0.95      0.95      1428
          1       0.96      0.96      0.96      1889

avg / total       0.96      0.96      0.96      3317

[[1354   74]
 [  70 1819]]


# Support Vector Machine (SVM) Classifier  

In [24]:
# Support Vector Machine
from sklearn import datasets
from sklearn import metrics
from sklearn.svm import SVC

# fit a SVM model to the data
model = SVC()
model.fit(X_train, y_train)
print(model)

# make predictions
expected = y_test
predicted = model.predict(X_test)

# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
             precision    recall  f1-score   support

         -1       0.94      0.92      0.93      1428
          1       0.94      0.96      0.95      1889

avg / total       0.94      0.94      0.94      3317

[[1312  116]
 [  82 1807]]


# MLP for binary classification (Keras)  *TEST ONLY*

In [8]:
import numpy as np
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.wrappers.scikit_learn import KerasClassifier


# # Generate dummy data
# x_train = np.random.random((1000, 20))
# y_train = np.random.randint(2, size=(1000, 1))
# x_test = np.random.random((100, 20))
# y_test = np.random.randint(2, size=(100, 1))

model = Sequential()
model.add(Dense(64, input_dim=29, activation='relu'))
model.add(Dropout(0.8))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.8))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

model.fit(X_train, y_train,
          epochs=20,
          batch_size=128)
score = model.evaluate(X_test, y_test, batch_size=128)

Epoch 1/10
7738/7738 [==============================] - 1s 70us/step - loss: 0.1540 - acc: 0.1044
Epoch 2/10
7738/7738 [==============================] - 0s 30us/step - loss: -1.0172 - acc: 0.0611

In [16]:
print(score)

[-5.5689168026036322, 0.51301726507761602]
